import { jsPDF } from "jspdf";
import { BotCommand } from "../types";

export const generateCommandsPDF = (commands: BotCommand[]) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(0, 100, 0); // Dark Green
  doc.text("MineMind Forge", 20, 20);
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Bot Command Reference & Reprogramming Guide", 20, 30);
  
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text("This document outlines the voice/chat commands available to reprogram", 20, 40);
  doc.text("AI companions in real-time. These commands must be issued by the Creator.", 20, 45);
  
  // Draw line
  doc.setLineWidth(0.5);
  doc.line(20, 50, 190, 50);

  let y = 65;
  
  commands.forEach((cmd) => {
    // Page break check
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    
    // Command Name
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(cmd.command.toUpperCase(), 20, y);
    
    // Usage
    doc.setFont("courier", "normal");
    doc.setFontSize(11);
    doc.setTextColor(50);
    doc.text(cmd.usage, 70, y);
    
    y += 7;
    
    // Description
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0);
    const splitDesc = doc.splitTextToSize(cmd.description, 170);
    doc.text(splitDesc, 20, y);
    
    y += (splitDesc.length * 5) + 2;
    
    // Example
    doc.setFont("courier", "italic");
    doc.setFontSize(10);
    doc.setTextColor(80);
    doc.text(`Example: ${cmd.example}`, 25, y);
    
    y += 12;
  });
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text(`Generated by MineMind Forge - ${new Date().toLocaleDateString()}`, 20, 285);

  doc.save("MineMind_Bot_Commands.pdf");
};