
import React, { useState } from 'react';
import { GeneratedFile, AppLanguage } from '../types';
import { UI_TEXT } from '../constants';
import { Copy, FileCode, Check, Download, Package, FileJson, FileType } from 'lucide-react';
import JSZip from 'jszip';

interface CodeViewerProps {
  files: GeneratedFile[];
  language: AppLanguage;
}

const CodeViewer: React.FC<CodeViewerProps> = ({ files, language }) => {
  const [selectedFileIndex, setSelectedFileIndex] = useState(0);
  const [copied, setCopied] = useState(false);
  const [isZipping, setIsZipping] = useState(false);
  const t = UI_TEXT[language];

  if (!files || files.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-gray-500 bg-[#0d1117]">
        <div className="w-20 h-20 bg-gray-800/50 rounded-full flex items-center justify-center mb-6 border border-gray-700">
           <FileCode className="w-10 h-10 opacity-50 text-green-500" />
        </div>
        <p className="text-xl font-medium text-gray-300">{t.noCode}</p>
        <p className="text-sm mt-2 text-gray-500">{t.configureMsg}</p>
      </div>
    );
  }

  const selectedFile = files[selectedFileIndex];

  const handleCopy = () => {
    navigator.clipboard.writeText(selectedFile.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadZip = async () => {
    setIsZipping(true);
    try {
      const zip = new JSZip();

      files.forEach(file => {
        zip.file(file.filename, file.content);
      });

      const readmeContent = `# MineMind Bot Project
Generated by MineMind Forge.

## Installation
1. Check the target platform (Paper/Fabric/Forge/NeoForge).
2. Build with Maven or Gradle.
3. Deploy JAR to server.
`;
      zip.file("README.md", readmeContent);

      const content = await zip.generateAsync({ type: "blob" });
      const url = window.URL.createObjectURL(content);
      const a = document.createElement("a");
      a.href = url;
      a.download = "MineMindBot_Source.zip";
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (error) {
      console.error("Failed to zip files", error);
    } finally {
      setIsZipping(false);
    }
  };

  const getShortName = (path: string) => {
    const parts = path.split('/');
    return parts[parts.length - 1];
  };

  const getFileIcon = (filename: string) => {
      if (filename.endsWith('.java')) return '☕';
      if (filename.endsWith('.json')) return <FileJson className="w-3.5 h-3.5" />;
      if (filename.endsWith('.xml') || filename.endsWith('.yml')) return <FileType className="w-3.5 h-3.5" />;
      return <FileCode className="w-3.5 h-3.5" />;
  };

  return (
    <div className="bg-[#0d1117] rounded-xl flex flex-col h-full overflow-hidden">
      {/* File Tabs & Actions */}
      <div className="flex items-center justify-between bg-[#161b22] border-b border-gray-800">
        <div className="flex overflow-x-auto scrollbar-thin scrollbar-thumb-gray-700 scrollbar-track-transparent">
          {files.map((file, index) => (
            <button
              key={`${file.filename}-${index}`}
              onClick={() => setSelectedFileIndex(index)}
              className={`px-4 py-3 text-xs font-mono border-r border-gray-800 flex items-center gap-2 whitespace-nowrap transition-all ${
                selectedFileIndex === index
                  ? 'bg-[#0d1117] text-green-400 border-t-2 border-t-green-500'
                  : 'text-gray-400 hover:bg-[#1c2128] hover:text-gray-200 border-t-2 border-t-transparent'
              }`}
              title={file.filename}
            >
              <span className="opacity-70 flex items-center">
                {getFileIcon(file.filename)}
              </span>
              {getShortName(file.filename)}
            </button>
          ))}
        </div>
        
        <div className="flex items-center px-3 py-2 gap-2 flex-shrink-0 bg-[#161b22] border-l border-gray-800 shadow-[-10px_0_15px_-3px_rgba(0,0,0,0.5)] z-10">
          <button
            onClick={handleDownloadZip}
            disabled={isZipping}
            className="flex items-center gap-2 px-3 py-1.5 rounded bg-green-700 hover:bg-green-600 text-white text-xs font-medium transition-all"
          >
             {isZipping ? <Package className="w-3.5 h-3.5 animate-bounce" /> : <Download className="w-3.5 h-3.5" />}
             {isZipping ? "..." : t.zip}
          </button>
        </div>
      </div>

      {/* Code Content */}
      <div className="relative flex-grow overflow-hidden flex flex-col">
         {/* Toolbar */}
        <div className="flex-shrink-0 p-2 flex justify-between items-center bg-[#0d1117] border-b border-gray-800 z-10">
          <div className="flex flex-col px-2">
            <span className="text-xs text-gray-500 font-mono break-all">{selectedFile.filename}</span>
          </div>
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-gray-800 text-gray-300 text-xs hover:bg-gray-700 border border-gray-700 transition-all flex-shrink-0"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? t.copied : t.copy}
          </button>
        </div>

        <div className="flex-grow overflow-auto custom-scrollbar p-4">
            <pre className="text-sm font-mono text-gray-300 leading-relaxed tab-4">
            <code>{selectedFile.content}</code>
            </pre>
        </div>
      </div>
    </div>
  );
};

export default CodeViewer;
